### PR TITLE
Create GOVERNANCE.md

### PR DESCRIPTION
**Pull request by jwbowers**
Add a statement about governance.

### CODE REVIEW

**Comment by jwbowers** [comment]
@maartenvoors @nahomi If you agree, let me know. Also feel free to edit.

**Comment by jwbowers** [comment]
@nahomi @maartenvoors See if you agree with the governance policy that I sketched. Would be nice to accept these changes as we start to add other links and such to the book.

**Comment by maartenvoors** [comment]
yes agreed!

Sorry just remembered I missed replying to this request – now cant find it on github issues (but may be looking on the wrong place...)

Thanks for drafting it,

M
________________________________

**Comment by jwbowers** [comment]
@nahomi  I am going to merge this pull request. We can change the GOVERNANCE doc if you have any additional thoughts.

**Pull request merged**
